- name: Display vars.
  ansible.builtin.debug:
    msg: |
      ai_at: {{ ai_at }}
      ai_async: {{ ai_async }}
      ai_cmd: {{ ai_cmd }}

- name: Execute the command async=3600 poll=0
  when: ai_async | bool
  block:

    - name: Execute command async=3600 poll=0
      async: 3600
      poll: 0
      ansible.builtin.shell:
        cmd: "{{ ai_cmd }}"

    - name: End of play.
      ansible.builtin.meta: end_play

- name: Schedule the command.
  block:

    - name: Schedule the command.
      ansible.builtin.command:
        cmd:  "at {{ ai_at | d('now', true) }}"
        stdin: "{{ ai_cmd }}"

    - name: Get scheduled jobs.
      register: out_atq
      ansible.builtin.command: atq

    - name: Display scheduled jobs.
      ansible.builtin.debug:
        var: out_atq.stdout
