---
_ai_repos: 'git://172.16.99.201'

ai_db_host:
  foo:
    repo_host: "{{ _ai_repos }}"
    repo: ansible-conf-test
    repo_dest: /root
    repo_playbook: pb-test.yml
  bar:
    repo_host: "{{ _ai_repos }}"
    repo: ansible-conf-test
    repo_dest: /root
    repo_playbook: pb-test.yml

ai_db_class_options:
  at: ''
  async: true

ai_db_class:
  log-server:
    repo_host: "{{ _ai_repos }}"
    repo: ansible-conf-syslogng-server
    repo_dest: /root
    repo_playbook: pb-logserv.yml
  log-client:
    repo_host: "{{ _ai_repos }}"
    repo: ansible-conf-syslogng-client
    repo_dest: /root
    repo_playbook: pb-logclient.yml
  test:
    repo_host: "{{ _ai_repos }}"
    repo: ansible-conf-test
    repo_dest: /root
    repo_playbook: pb-test.yml
